"""First-run bootstrap.

Steps:
  1. Generate or accept a KEK (32 random bytes, base64).
  2. Write KEK + DSN to mvghb/.env (if not present).
  3. Apply mvghb db schema (db/0001_mvghb.sql) to noc-gov.
  4. Seed the actor registry (orchestrator, producing_agent,
     adversarial_agent, human).
  5. Emit one 'genesis' chain entry per actor with prev_chain_id=NULL.
  6. Commit one initial master_anchor.
"""
from __future__ import annotations

import base64
import os
import secrets
from pathlib import Path

from sqlalchemy import text

from mvghb.chain_write.writer import ChainWriter
from mvghb.common import actors as actor_reg
from mvghb.common.db import gov_session
from mvghb.common.log import log
from mvghb.common.settings import get_settings
from mvghb.master_anchor import commit_anchor


REPO_ROOT = Path(__file__).resolve().parents[3]
MVGHB_ROOT = REPO_ROOT / "mvghb"
ENV_PATH = MVGHB_ROOT / ".env"
SCHEMA_PATH = MVGHB_ROOT / "db" / "0001_mvghb.sql"


def generate_kek_b64() -> str:
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def _write_env(kek_b64: str, gov_dsn: str) -> Path:
    if ENV_PATH.exists():
        existing = ENV_PATH.read_text()
        if "MVGHB_KEK=" in existing:
            log.info("mvghb.bootstrap.env_already_present", path=str(ENV_PATH))
            return ENV_PATH
    body = (
        f"# mvghb dev env — generated by `mvghb bootstrap init`.\n"
        f"# DO NOT commit this file. KEK is dev-only; production uses Vault.\n"
        f"MVGHB_KEK={kek_b64}\n"
        f"MVGHB_GOV_DSN={gov_dsn}\n"
        f"MVGHB_SYSTEM_VERSION=mvghb-w1-0.1.0\n"
        f"MVGHB_WAL_DIR=/tmp/mvghb-wal\n"
    )
    ENV_PATH.write_text(body)
    log.info("mvghb.bootstrap.env_written", path=str(ENV_PATH))
    return ENV_PATH


def apply_schema() -> None:
    from mvghb.common.sql_apply import apply_sql_file
    with gov_session() as s, s.begin():
        n = apply_sql_file(s, SCHEMA_PATH)
    log.info("mvghb.bootstrap.schema_applied",
             file=str(SCHEMA_PATH), statements=n)


def write_genesis_entries(writer: ChainWriter) -> dict[str, str]:
    """For each default actor without a genesis_chain_id, emit a
    'genesis' chain entry with prev_chain_id=NULL and record the
    chain_id back into mvghb_actor.genesis_chain_id.
    """
    minted: dict[str, str] = {}
    for actor_id, role, tier in actor_reg.DEFAULT_ACTORS:
        with gov_session() as s, s.begin():
            actor_reg.upsert_actor(
                s, actor_id=actor_id, actor_role=role, ownership_tier=tier,
            )
            existing = actor_reg.get_actor(s, actor_id)
            if existing and existing.genesis_chain_id is not None:
                log.info("mvghb.bootstrap.genesis_skip",
                         actor_id=actor_id,
                         chain_id=str(existing.genesis_chain_id))
                continue
        # Genesis emit — chain head is currently None for this actor.
        res = writer.emit(
            entry_type="genesis",
            actor_id=actor_id,
            actor_role=role,
            incident_id=None,
            payload_ref={
                "actor_id": actor_id,
                "actor_role": role,
                "ownership_tier": tier,
                "note": "MVGH-β Wave 1 genesis entry — prev_chain_id=NULL anchors this actor's chain.",
            },
        )
        with gov_session() as s, s.begin():
            actor_reg.set_genesis(s, actor_id=actor_id, chain_id=res.chain_id)
        minted[actor_id] = str(res.chain_id)
        log.info("mvghb.bootstrap.genesis_emitted",
                 actor_id=actor_id, chain_id=str(res.chain_id))
    return minted


def init_first_run(*, gov_dsn: str | None = None) -> dict:
    """End-to-end first-run init. Idempotent — safe to re-run."""
    gov_dsn = gov_dsn or os.environ.get(
        "MVGHB_GOV_DSN",
        "postgresql+psycopg://noc:noc@localhost:5434/noc_gov",
    )
    kek_b64 = os.environ.get("MVGHB_KEK") or generate_kek_b64()
    _write_env(kek_b64, gov_dsn)
    # Make settings reflect what we just wrote.
    os.environ.setdefault("MVGHB_KEK", kek_b64)
    os.environ.setdefault("MVGHB_GOV_DSN", gov_dsn)
    from mvghb.common.settings import reset_settings_cache
    reset_settings_cache()
    settings = get_settings()

    apply_schema()
    writer = ChainWriter()
    genesis_ids = write_genesis_entries(writer)
    anchor = commit_anchor(writer=writer)

    return {
        "kek_id": settings.kek_id,
        "env_path": str(ENV_PATH),
        "genesis_chain_ids": genesis_ids,
        "first_anchor_id": str(anchor.anchor_id) if anchor else None,
        "first_anchor_chain_id": str(anchor.anchor_chain_id) if anchor else None,
    }
